### ISSUE TITLE
Missing Resources causes error opening project

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/ArcProViewer#2]
@philipbaileynar 
![image](https://github.com/Riverscapes/ArcProViewer/assets/97305413/795f7ff3-9fd0-4700-a018-69f466ccf0a7)

I had exported this project from 0.3.23 in QRIS and it opens in Q Riverscapes Viewer.

Same error for all project types.

**Comment by philipbaileynar** [comment]
@Jdgilby updated resources and now it opens projects OK. The addin does not ship with any resources upon install.

TODO: Check for absence of resource folder when opening a project and warn the user if its not present. i.e. an indication that the user has yet to update resources.

**Comment by philipbaileynar** [comment]
<img width="430" alt="Screenshot 2024-07-09 at 2 44 13 PM" src="https://github.com/Riverscapes/ArcProViewer/assets/8645379/65d3e7af-1c62-40ca-a8d5-1e8c08b37984">
